(*
Built a custom Flight Path API using Wolfram Mathematica
To call the API, use the format url?x=<airport code>
*)

api = CloudDeploy[APIFunction["x" -> "String", GeoGraphics[{Red,
       Polygon[EntityValue[Entity["Airport", "SYR"], "Countries"]], 
       Green, Polygon[
        EntityValue[Entity["Airport", #x], "Countries"]], Red, Thick, 
       GeoPath[{Entity["Airport", "SYR"], Entity["Airport", #x]}]
       }, 
      PlotLabel -> 
       Grid[{{Style["Generated by Wolfram|Alpha API", Brown, 
           FontFamily -> "Alegreya SC"]}, {Style[
           "Destination: " <> Entity["Airport", #x]["Name"], 
           Gray]}, {Style[
           "Origin: " <> Entity["Airport", "SYR"]["Name"], 
           Gray]}}]] &, "PNG"], Permissions -> "Public"];